
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sparkapplications.sparkoperator
spec:
  group: sparkoperator
  names:
    kind: SparkApplication
    plural: sparkapplications
  scope: ""
  versions:
    - name: v1beta1
      served: true
      storage: false
    - name: v1alpha1
      served: true
      storage: false
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
